from enum import Enum, auto


class Sig(Enum):
    INIT = auto()
    LOGIN = auto()
    LOGIN_SUCCESS = auto()
    LOGIN_FAILURE = auto()
    NETWORK_FAILURE = auto()
    EXT = auto()
    EXT_GET = auto()
    EXT_SET = auto()
    EXT_SUCCESS = auto()
    FILES_LIST = auto()
    REGISTER = auto()
    PATH_GET = auto()
    PATH_SET = auto()
    FILES_SET = auto()
    FILES_GET = auto()
    PARSE = auto()
    CWD_GET = auto()
    REFRESH = auto()
    SIGINT = auto()
    NONE = auto()
    ERROR = auto()
    FILES_REINDEX = auto()
    PLAY = auto()
    PLAY_ALL = auto()
    PLAY_RANGE = auto()
    STOP = auto()
    DONE = auto()
    PLAY_PAUSE = auto()
    NEXT = auto()
    PREVIOUS = auto()
    STATE_CHANGE = auto()
    VOLUME = auto()
    MPV_EVENT = auto()
    DISPATCH_ERROR = auto()
    PING = auto()
    PONG = auto()
    OPEN = auto()
    SEEK = auto()
    VOLUME_INC = auto()
    SEARCH = auto()
    SEARCH_ALL = auto()
    POPUP = auto()
    LOGS = auto()
    PUSH = auto()
    GET = auto()
    POISON = auto()
    
